name: Repo builder

on:
  workflow_dispatch:
jobs:
  pipewire:
    uses: ./.github/workflows/pipewire-builder.yml

  nvidia-tkg:
    uses: ./.github/workflows/nvidia-tkg-builder.yml

  wine-staging:
    uses: ./.github/workflows/wine-builder.yml

  linux-tkg:
    uses: ./.github/workflows/linux-tkg-builder.yml
