# This is a basic workflow that is manually triggered

name: Repo builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  pipewire:
    uses: ./.github/workflows/pipewire-builder.yml

  nvidia-tkg:
    uses: ./.github/workflows/nvidia-tkg-builder.yml

  wine-staging:
    uses: ./.github/workflows/wine-builder.yml

  linux-tkg:
    uses: ./.github/workflows/linux-tkg-builder.yml
