name: Repo builder

on:
  workflow_dispatch:
jobs:
  pipewire:
    uses: ./.github/workflows/pipewire-builder.yml
    secrets: inherit

  nvidia-tkg:
    uses: ./.github/workflows/nvidia-tkg-builder.yml
    secrets: inherit

  wine-staging:
    uses: ./.github/workflows/wine-builder.yml
    secrets: inherit

  linux-tkg:
    uses: ./.github/workflows/linux-tkg-builder.yml
    secrets: inherit

  packdb:
    if: ${{ always() }}
    needs: [pipewire, nvidia-tkg, wine-staging, linux-tkg]
    uses: ./.github/workflows/packdb.yml
    secrets: inherit
