# This is a basic workflow that is manually triggered

name: GETVARS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  pack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Setup container
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo git archlinux-keyring rsync openssh
          sed -i 's,exit $E_ROOT,echo but you know what you do,' /usr/bin/makepkg
          echo -e "PACKAGER=\"Ihor Yemaiev <mynameiskitsune@proton.me>\"\nGPGKEY=\"128753272FB3D91D\"" >> /etc/makepkg.conf
          mkdir -p /root/.ssh/
          echo "${{ secrets.SSH_PRIVATE }}" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB }}" > /root/.ssh/known_hosts

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASS }}

      - name: GET
        run: |
          mkdir /tmp/x86_64
          cd /tmp/x86_64/
          echo "${{ secrets.SSH_CLEAR }}" > comm.SSH_CLEAR
          echo "${{ secrets.RSYNC_COMMAND }}" > comm.RSYNC_PUSH
          echo "${{ secrets.RSYNC_GET }}" > comm.RSYNC_GET
          echo "${{ secrets.SSH_PUB }}" > comm.SSH_PUB
          echo "${{ secrets.SSH_PRIVATE }}" > comm.SSH_PRIVATE
          eval "${{ secrets.RSYNC_COMMAND }}"
          
          
