# This is a basic workflow that is manually triggered

name: TKG-kernel builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
        packdb:
            type: boolean
            description: Pack repo database
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
        options: --oom-kill-disable --memory-swap -1
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Setup container
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          echo -e "[deadyokai]\nServer = https://repo.vilafox.xyz/x86_64" >> /etc/pacman.conf
          sed -i "s/SigLevel/#SigLevel/g" /etc/pacman.conf
          sed -i "s/LocalFileSigLevel/#LocalFileSigLevel/g" /etc/pacman.conf
          sed -i "s/RemoteFileSigLevel/#RemoteFileSigLevel/g" /etc/pacman.conf
          sed -i "s/\[options\]/\[options\]\nSigLevel = Never/g" /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo git archlinux-keyring wget linux-headers rsync openssh schedtool
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          sed -i 's,exit $E_ROOT,echo but you know what you do,' /usr/bin/makepkg
          echo -e "PACKAGER=\"Ihor Yemaiev <mynameiskitsune@proton.me>\"\nGPGKEY=\"128753272FB3D91D\"" >> /etc/makepkg.conf
          mkdir -p /root/.ssh/
          echo "${{ secrets.SSH_PRIVATE }}" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB }}" > /root/.ssh/known_hosts
          mkdir /tmp/x86_64

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASS }}

      - name: Build kernel TKG
        run: |
          git clone https://github.com/Frogging-Family/linux-tkg.git /tmp/linux
          cd /tmp/linux
          echo "Write config"
          sed -i 's/_cpusched=\"\"/_cpusched=\"pds\"/g' customization.cfg
          sed -i 's/_compiler=\"\"/_compiler=\"llvm\"/g' customization.cfg
          # sed -i 's/_lto_mode=\"\"/_lto_mode=\"full\"/g' customization.cfg
          sed -i 's/_lto_mode=\"\"/_lto_mode=\"no\"/g' customization.cfg
          sed -i 's/_sched_yield_type=\"\"/_sched_yield_type=\"0\"/g' customization.cfg
          sed -i 's/_rr_interval=\"\"/_rr_interval=\"default\"/g' customization.cfg
          sed -i 's/_processor_opt=\"\"/_processor_opt=\"generic_v3\"/g' customization.cfg
          sed -i 's/_timer_freq=\"\"/_timer_freq=\"1000\"/g' customization.cfg
          sed -i 's/_default_cpu_gov=\"\"/_default_cpu_gov=\"performance\"/g' customization.cfg
          sed -i 's/_tickless=\"\"/_tickless=\"1\"/g' customization.cfg
          sed -i 's/_acs_override=\"\"/_acs_override=\"false\"/g' customization.cfg
          sed -i 's/_anbox=\"\"/_anbox=\"false\"/g' customization.cfg
          sed -i 's/_config_fragments_no_confirm=\"\"/_config_fragments_no_confirm=\"true\"/g' customization.cfg
          sed -i 's/_menunconfig=\"\"/_menunconfig=\"false\"/g' customization.cfg
          sed -i 's/_diffconfig=\"\"/_diffconfig=\"false\"/g' customization.cfg
          echo -e "_custom_pkgbase=\"linux-tkg-pds-llvm\"\n" >> customization.cfg
          sed -i 's/_numadisable=\"false\"/_numadisable=\"true\"/g' customization.cfg
          cat customization.cfg
          echo | PKGDEST=/tmp/x86_64 makepkg --noconfirm -s --sign

      - name: Upload files
        run: |
          ls -la /tmp/x86_64/
          cd /tmp/x86_64/
          #repo-add --verify --sign deadyokai.db.tar.gz *.pkg.tar.zst
          eval "${{ secrets.RSYNC_COMMAND }}"
        

  packdb:
    if: ${{ github.event.inputs.packdb == 'true' }}
    needs: [build]
    uses: ./.github/workflows/packdb.yml
    secrets: inherit

          

