# This is a basic workflow that is manually triggered

name: OBS builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
        packdb:
            type: boolean
            description: Pack repo database
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Setup container
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo git archlinux-keyring wget linux-headers rsync openssh pipewire-jack
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          sed -i 's,exit $E_ROOT,echo but you know what you do,' /usr/bin/makepkg
          echo -e "PACKAGER=\"Ihor Yemaiev <mynameiskitsune@proton.me>\"\nGPGKEY=\"128753272FB3D91D\"" >> /etc/makepkg.conf
          mkdir -p /root/.ssh/
          echo "${{ secrets.SSH_PRIVATE }}" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB }}" > /root/.ssh/known_hosts
          mkdir /tmp/x86_64
          # eval "${{ secrets.RSYNC_GET }}"

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASS }}
          
      - name: Build OBS dependencies
        run: |
          echo "::group::ffmpeg"
          git clone https://aur.archlinux.org/ffmpeg-obs.git /tmp/ff
          cd /tmp/ff
          PKGDEST=/tmp/x86_64 makepkg --noconfirm -s --sign
          echo "::endgroup"
          echo "::group::ftl-sdk"
          git clone https://aur.archlinux.org/ftl-sdk.git /tmp/ftl
          cd /tmp/ftl
          PKGDEST=/tmp/x86_64 makepkg --noconfirm -s --sign
          echo "::endgroup"
          echo "::group::vlc-luajit"
          git clone https://aur.archlinux.org/vlc-luajit.git /tmp/vlc-luajit
          cd /tmp/vlc-luajit
          PKGDEST=/tmp/x86_64 makepkg --noconfirm -s --sign
          echo "::endgroup"
          echo "::group::cef-minimal-obs-bin"
          git clone https://aur.archlinux.org/cef-minimal-obs-bin.git /tmp/cef-minimal-obs-bin
          cd /tmp/cef-minimal-obs-bin
          PKGDEST=/tmp/x86_64 makepkg --noconfirm -s --sign
          echo "::endgroup"

      - name: Build OBS
        run: |
          git clone https://aur.archlinux.org/obs-studio-browser.git /tmp/obs
          cd /tmp/obs
          PKGDEST=/tmp/x86_64 makepkg --noconfirm -s --sign

      - name: Upload files
        run: |
          ls -la /tmp/x86_64/
          cd /tmp/x86_64/
          #repo-add --verify --sign deadyokai.db.tar.gz *.pkg.tar.zst
          eval "${{ secrets.RSYNC_COMMAND }}"
          
          

  packdb:
    if: ${{ github.event.inputs.packdb == 'true' }}
    needs: [build]
    uses: ./.github/workflows/packdb.yml
    secrets: inherit
