# This is a basic workflow that is manually triggered

name: OBS builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
        packdb:
            type: boolean
            description: Pack repo database
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Setup container
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          echo -e "[deadyokai]\nServer = https://repo.vilafox.xyz/x86_64" >> /etc/pacman.conf
          sed -i "s/SigLevel/#SigLevel/g" /etc/pacman.conf
          sed -i "s/LocalFileSigLevel/#LocalFileSigLevel/g" /etc/pacman.conf
          sed -i "s/RemoteFileSigLevel/#RemoteFileSigLevel/g" /etc/pacman.conf
          sed -i "s/\[options\]/\[options\]\nSigLevel = Never/g" /etc/pacman.conf
          pacman --noconfirm -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
          echo -e "[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf
          pacman -Syyu --noconfirm base-devel sudo git archlinux-keyring wget linux-headers rsync openssh pipewire-jack mbedtls2
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          sed -i 's,exit $E_ROOT,echo but you know what you do,' /usr/bin/makepkg
          echo -e "PACKAGER=\"Ihor Yemaiev <mynameiskitsune@proton.me>\"\nGPGKEY=\"128753272FB3D91D\"" >> /etc/makepkg.conf
          mkdir -p /root/.ssh/
          echo "${{ secrets.SSH_PRIVATE }}" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB }}" > /root/.ssh/known_hosts
          mkdir /tmp/x86_64
          # eval "${{ secrets.RSYNC_GET }}"

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASS }}

      - name: Build OBS
        run: |
          mv ${GITHUB_WORKSPACE}/other-pkgs/obs /tmp/obs
          cd /tmp/obs
          PKGDEST=/tmp/x86_64 makepkg --noconfirm -s --sign

      - name: Upload files
        run: |
          ls -la /tmp/x86_64/
          cd /tmp/x86_64/
          #repo-add --verify --sign deadyokai.db.tar.gz *.pkg.tar.zst
          eval "${{ secrets.RSYNC_COMMAND }}"
          
          

  packdb:
    if: ${{ github.event.inputs.packdb == 'true' }}
    needs: [build]
    uses: ./.github/workflows/packdb.yml
    secrets: inherit
