# This is a basic workflow that is manually triggered

name: Database packing

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  pack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Packing database
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: "80.208.225.101"
            username: "archrepo"
            key: ${{ secrets.SSH_PRIVATE }}
            port: 22
            script: |
                rm -rf ~/tempdb
                mv ~/x86_64 ~/tempdb
                mkdir ~/x86_64
                cd ~/x86_64
                repo-add --verify --sign deadyokai.db.tar.gz ~/tempdb/*.pkg.tar.zst
                for file in $(tar tzf deadyokai.files.tar.gz | awk -F/ '{ print $1 }' | uniq); do mv ~/tempdb/$file-*.pkg.tar.zst .; done
                for file in $(tar tzf deadyokai.files.tar.gz | awk -F/ '{ print $1 }' | uniq); do mv ~/tempdb/$file-*.pkg.tar.zst.sig .; done
