# This is a basic workflow that is manually triggered

name: PipeWire builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Setup container
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo git
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir /home/user
          chown user -R /home/user
          chown user -R .
          chown user -R ${GITHUB_WORKSPACE}
          
    
      - uses: actions/checkout@v2
          
      - name: Compile
        run: |
          echo -e "PACKAGER=\"Ihor Yemaiev <mynameiskitsune@proton.me>\"\nGPGKEY=\"128753272FB3D91D\"" >> /etc/makepkg.conf
          cat /etc/makepkg.conf
          su user -c "gpg --import ${GITHUB_WORKSPACE}/kitsune.gpg"
          echo "______LIST_KEYS______"
          gpg --list-keys
          echo "______LIST_KEYS_USER______"
          su user -c "gpg --list-keys"
          su user -c "git clone https://aur.archlinux.org/pipewire-full-git.git /tmp/pw"
          echo "${{ secrets.PRIVATE_KEY }}" | base64 --decode > /tmp/key
          echo "${{ secrets.GPG_PASS }}" | gpg --batch --yes --passphrase-fd 0 --import /tmp/key
          su user -c "echo \"${{ secrets.GPG_PASS }}\" | gpg --batch --yes --passphrase-fd 0 --import /tmp/key"
          rm /tmp/key
          su user -c "cd /tmp/pw && yes|PKGDEST=/tmp/x86_64 makepkg --noconfirm -s --sign"
          
      - name: Pack db
        run: |
          chown user -R ${GITHUB_WORKSPACE}
          chown user -R ${GITHUB_WORKSPACE}/x86_64
          su user -c "mv -f /tmp/x86_64/* ${GITHUB_WORKSPACE}/x86_64"
          ls -la ${GITHUB_WORKSPACE}
          su user -c "cd ${GITHUB_WORKSPACE}/x86_64 && repo-add --verify --sign deadyokai.db.tar.gz *.pkg.tar.zst"
          cd ${GITHUB_WORKSPACE}
          
      - name: Push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Repo update
        
          
          
