# This is a basic workflow that is manually triggered

name: PipeWire builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
      - name: Setup container
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo git
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
              
      - uses: actions/checkout@v2
          
      - name: Compile
        run: |
          chown user -R .
          chown user -R ${GITHUB_WORKSPACE}
          echo -e "PACKAGER=\"Ihor Yemaiev <mynameiskitsune@proton.me>\"\nGPGKEY=\"128753272FB3D91D\"" >> /etc/makepkg.conf
          su user -c "gpg --import ${GITHUB_WORKSPACE}/kitsune.gpg"
          pacman-key --add ${GITHUB_WORKSPACE}/kitsune.gpg
          su user -c "git clone https://aur.archlinux.org/pipewire-full-git.git /tmp/pw"
          su user -c "cd /tmp/pw && yes|PKGDEST=/tmp/x86_64 makepkg --noconfirm -s"
          
      - name: Pack db
        run: |
          su user -c "mv -f /tmp/x86_64/* ${GITHUB_WORKSPACE}/x86_64"
          ls -la ${GITHUB_WORKSPACE}
          su user -c "cd ${GITHUB_WORKSPACE}/x86_64 && repo-add --verify --sign deadyokai.db.tar.gz *.pkg.tar.zst"
          cd ${GITHUB_WORKSPACE}
          
      - name: Push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Repo update
        
          
          
